version: '2'
services:
  firefox:
    image: selenium/node-firefox-debug
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      TZ: America/Montreal
      SCREEN_WIDTH: 1024
      SCREEN_HEIGHT: 768
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      TZ: Australia/Canberra
      HUB_HOST: hub

  hub:
    image: selenium/hub
    ports:
      - "4444:4444"


  bulletin:
    image: bulletin_board:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - hub
    ports:
      - "8080:8080"

  test:
    image: watir:latest
    build:
      context: ./
      dockerfile: ./Dockerfile_Watir_Wait
    depends_on:
      - bulletin
    volumes:
      - .:/tmp
    command: ["./wait-for-grid.sh", "ruby", "/tmp/bulletin_board.rb"]
